# Copy this file to loves/config.yaml.

# Fill in the details. Create the empty playlist first,
# and right-click > Share > Copy link to get the 
# playlist ID. The ID is the part after "playlist/"
# in the URL. You can change the other values, too.

# These default settings update your Loved Artists playlist with up to 50
# tracks: 10 each from your top five artists of the last 12 months as 
# scrobbled to Last.fm over the life of your Last.fm account.
# Tracks are selected randomly from the top 1000 tracks of that time period.
#
# Supported periods: overall, 7day, 1month, 3month, 6month, 12month
#
# Set track_pool_order to sequential, if you prefer to select each artist's track
# in most-played order descending. Default is random.
# 
# Set playlist_order to alternating to have tracks interleaved by artist. Default
# is random.
#
# lastfm_page_size determines how many tracks are pulled from Last.fm
# with each request.
#
# Additional artists may optionally be included via include_artists.
# List them like this:
#
#  include_artists:
#    - "Guster"
#    - "Crowded House"
#
loves:
  artist_period: 1month
  top_artist_count: 10
  track_period: overall
  tracks_per_artist: 10
  track_pool_order: random
  track_pool_size: 2500
  lastfm_page_size: 100
  playlist_id: "your-loves-playlist-id"
  playlist_order: alternating
  include_artists: []
