# Build a playlist that lets every traveler have a say.
#
# Every traveler supplies tracks to be compiled into a single playlist that will
# be as long as the trip's duration.
#
# Tracks may be submitted in spotify playlist form, in .m3u format, or in a text
# file where tracks are listed one per line as "artist - track"
#
# source_track_order is either "random" or "sequential"
# destination_track_order is either "random" or "alternating"
#

trip_duration_minutes: 480
destination_playlist_id: "spotify_playlist_id_here"
source_track_order: random
destination_track_order: random

travelers:
  - name: Mom
    source_type: spotify
    source: "spotify_playlist_id_here"
  - name: Dad
    source_type: m3u
    source: "./sources/dad.m3u"
  - name: Brother
    source_type: text
    source: "./sources/brother.txt"
  - name: Sister
    source_type: text
    source: "./sources/sister.txt"